// const allPokemon = [
//   "Clefable",
//   "Bisharp",
//   "Blissey",
//   "Corviknight",
//   "Dragapult",
//   "Dragonite",
//   "Excadrill",
//   "Ferrothorn",
//   "Garchomp",
//   "Hawlucha",
//   "Heatran",
//   "Hippowdon",
//   "Hydreigon",
//   "Kartana",
//   "Kyurem",
//   "Landorus-Therian",
//   "Magnezone",
//   "Mandibuzz",
//   "Melmetal",
//   "Mew",
//   "Rillaboom",
//   "Scizor",
//   "Skarmory",
//   "Slowbro",
//   "Slowking",
//   "Slowking-Galar",
//   "Swampert",
//   "Tapu Fini",
//   "Tapu Koko",
//   "Tapu Lele",
//   "Tornadus-Therian",
//   "Toxapex",
//   "Tyranitar",
//   "Urshifu-Rapid-Strike",
//   "Volcarona",
//   "Weavile",
//   "Zapdos",
//   "Zeraora",
//   "Alakazam",
//   "Arctozolt",
//   "Blacephalon",
//   "Blaziken",
//   "Dracozolt",
//   "Gengar",
//   "Latias",
//   "Latios",
//   "Terrakion",
//   "Thundurus",
//   "Victini",
//   "Zapdos-Galar",
//   "Aegislash",
//   "Amoonguss",
//   "Azelf",
//   "Azumarill",
//   "Buzzwole",
//   "Celesteela",
//   "Chansey",
//   "Conkeldurr",
//   "Crawdaunt",
//   "Grimmsnarl",
//   "Gyarados",
//   "Hatterene",
//   "Jirachi",
//   "Keldeo",
//   "Keldeo-Resolute",
//   "Kommo-o",
//   "Krookodile",
//   "Lycanroc-Dusk",
//   "Mamoswine",
//   "Moltres",
//   "Moltres-Galar",
//   "Nidoking",
//   "Nihilego",
//   "Pelipper",
//   "Primarina",
//   "Regieleki",
//   "Rhyperior",
//   "Rotom-Heat",
//   "Rotom-Wash",
//   "Salamence",
//   "Slowbro-Galar",
//   "Tangrowth",
//   "Tapu Bulu",
//   "Tentacruel",
//   "Thundurus-Therian",
//   "Zarude",
//   "Zarude-Dada",
//   "Zygarde-10%",
//   "Diggersby",
//   "Haxorus",
//   "Mienshao",
//   "Scolipede",
//   "Venusaur",
//   "Barraskewda",
//   "Chandelure",
//   "Cloyster",
//   "Cobalion",
//   "Crobat",
//   "Darmanitan",
//   "Doublade",
//   "Flygon",
//   "Gardevoir",
//   "Gastrodon",
//   "Golisopod",
//   "Heracross",
//   "Incineroar",
//   "Klefki",
//   "Marowak-Alola",
//   "Metagross",
//   "Milotic",
//   "Mimikyu",
//   "Necrozma",
//   "Nidoqueen",
//   "Ninetales-Alola",
//   "Noivern",
//   "Obstagoon",
//   "Politoed",
//   "Polteageist",
//   "Polteageist-Antique",
//   "Porygon2",
//   "Raikou",
//   "Regidrago",
//   "Registeel",
//   "Reuniclus",
//   "Roserade",
//   "Seismitoad",
//   "Sharpedo",
//   "Snorlax",
//   "Stakataka",
//   "Steelix",
//   "Suicune",
//   "Togekiss",
//   "Toxtricity",
//   "Toxtricity-Low-Key",
//   "Umbreon",
//   "Volcanion",
//   "Weezing-Galar",
//   "Xurkitree",
//   "Barbaracle",
//   "Bewear",
//   "Cresselia",
//   "Durant",
//   "Entei",
//   "Indeedee",
//   "Linoone",
//   "Lucario",
//   "Pangoro",
//   "Porygon-Z",
//   "Sigilyph",
//   "Slurpuff",
//   "Tornadus",
//   "Aerodactyl",
//   "Araquanid",
//   "Arcanine",
//   "Blastoise",
//   "Braviary",
//   "Bronzong",
//   "Celebi",
//   "Comfey",
//   "Copperajah",
//   "Decidueye",
//   "Dhelmise",
//   "Diancie",
//   "Dragalge",
//   "Drapion",
//   "Escavalier",
//   "Espeon",
//   "Exploud",
//   "Garbodor",
//   "Glastrier",
//   "Golurk",
//   "Goodra",
//   "Guzzlord",
//   "Heliolisk",
//   "Inteleon",
//   "Mantine",
//   "Mudsdale",
//   "Ninjask",
//   "Rotom-Mow",
//   "Salazzle",
//   "Sirfetch’d",
//   "Starmie",
//   "Sylveon",
//   "Talonflame",
//   "Tauros",
//   "Toxicroak",
//   "Tyrantrum",
//   "Vaporeon",
//   "Vileplume",
//   "Xatu",
//   "Zoroark",
//   "Clawitzer",
//   "Duraludon",
//   "Exeggutor-Alola",
//   "Indeedee-F",
//   "Kingdra",
//   "Kingler",
//   "Machamp",
//   "Omastar",
//   "Raichu-Alola",
//   "Sceptile",
//   "Virizion",
//   "Absol",
//   "Aggron",
//   "Archeops",
//   "Aromatisse",
//   "Articuno-Galar",
//   "Charizard",
//   "Claydol",
//   "Druddigon",
//   "Froslass",
//   "Galvantula",
//   "Gigalith",
//   "Hitmonlee",
//   "Hitmontop",
//   "Jolteon",
//   "Lanturn",
//   "Lycanroc",
//   "Mesprit",
//   "Palossand",
//   "Passimian",
//   "Quagsire",
//   "Regirock",
//   "Ribombee",
//   "Sandaconda",
//   "Sandslash",
//   "Scrafty",
//   "Scyther",
//   "Silvally-Fairy",
//   "Silvally-Ghost",
//   "Silvally-Steel",
//   "Togedemaru",
//   "Tsareena",
//   "Weezing",
//   "Whimsicott",
//   "Abomasnow",
//   "Accelgor",
//   "Alcremie",
//   "Altaria",
//   "Appletun",
//   "Arctovish",
//   "Armaldo",
//   "Articuno",
//   "Audino",
//   "Aurorus",
//   "Avalugg",
//   "Basculin",
//   "Basculin-Blue-Striped",
//   "Beartic",
//   "Beheeyem",
//   "Bellossom",
//   "Boltund",
//   "Bouffalant",
//   "Butterfree",
//   "Calyrex",
//   "Carbink",
//   "Carracosta",
//   "Centiskorch",
//   "Cherrim",
//   "Cinccino",
//   "Coalossal",
//   "Cofagrigus",
//   "Corsola",
//   "Cradily",
//   "Cramorant",
//   "Crustle",
//   "Cryogonal",
//   "Cursola",
//   "Dedenne",
//   "Delibird",
//   "Ditto",
//   "Drampa",
//   "Drednaw",
//   "Drifblim",
//   "Dubwool",
//   "Dugtrio",
//   "Dugtrio-Alola",
//   "Dunsparce",
//   "Dusknoir",
//   "Eiscue",
//   "Eldegoss",
//   "Electivire",
//   "Emolga",
//   "Exeggutor",
//   "Falinks",
//   "Farfetch’d",
//   "Flapple",
//   "Flareon",
//   "Frosmoth",
//   "Gallade",
//   "Glaceon",
//   "Glalie",
//   "Golduck",
//   "Gothitelle",
//   "Gourgeist",
//   "Gourgeist-Large",
//   "Gourgeist-Small",
//   "Gourgeist-Super",
//   "Grapploct",
//   "Greedent",
//   "Heatmor",
//   "Hitmonchan",
//   "Jellicent",
//   "Jynx",
//   "Kabutops",
//   "Kangaskhan",
//   "Klinklang",
//   "Lapras",
//   "Leafeon",
//   "Lickilicky",
//   "Liepard",
//   "Lilligant",
//   "Lopunny",
//   "Ludicolo",
//   "Lunatone",
//   "Lurantis",
//   "Luxray",
//   "Lycanroc-Midnight",
//   "Magmortar",
//   "Malamar",
//   "Manectric",
//   "Maractus",
//   "Marowak",
//   "Mawile",
//   "Meltan",
//   "Meowstic",
//   "Meowstic-F",
//   "Miltank",
//   "Morpeko",
//   "Mr. Mime",
//   "Mr. Rime",
//   "Musharna",
//   "Ninetales",
//   "Noctowl",
//   "Octillery",
//   "Oranguru",
//   "Orbeetle",
//   "Perrserker",
//   "Persian",
//   "Persian-Alola",
//   "Pikachu-Alola",
//   "Pikachu-Hoenn",
//   "Pikachu-Kalos",
//   "Pikachu-Original",
//   "Pikachu-Partner",
//   "Pikachu-Sinnoh",
//   "Pikachu-Unova",
//   "Pikachu-World",
//   "Pincurchin",
//   "Pinsir",
//   "Poliwrath",
//   "Pyukumuku",
//   "Qwilfish",
//   "Raichu",
//   "Rapidash",
//   "Rapidash-Galar",
//   "Regice",
//   "Regigigas",
//   "Relicanth",
//   "Rotom",
//   "Rotom-Fan",
//   "Rotom-Frost",
//   "Runerigus",
//   "Sableye",
//   "Sandslash-Alola",
//   "Sawk",
//   "Seaking",
//   "Shedinja",
//   "Shiftry",
//   "Shiinotic",
//   "Shuckle",
//   "Silvally",
//   "Silvally-Bug",
//   "Silvally-Dark",
//   "Silvally-Dragon",
//   "Silvally-Electric",
//   "Silvally-Fighting",
//   "Silvally-Fire",
//   "Silvally-Flying",
//   "Silvally-Grass",
//   "Silvally-Ground",
//   "Silvally-Ice",
//   "Silvally-Poison",
//   "Silvally-Psychic",
//   "Silvally-Rock",
//   "Silvally-Water",
//   "Skuntank",
//   "Solrock",
//   "Spiritomb",
//   "Stonjourner",
//   "Stoutland",
//   "Stunfisk",
//   "Stunfisk-Galar",
//   "Sudowoodo",
//   "Swoobat",
//   "Thievul",
//   "Throh",
//   "Torkoal",
//   "Trevenant",
//   "Turtonator",
//   "Unfezant",
//   "Uxie",
//   "Vanilluxe",
//   "Vespiquen",
//   "Vikavolt",
//   "Wailord",
//   "Walrein",
//   "Whiscash",
//   "Wigglytuff",
//   "Wishiwashi",
//   "Wobbuffet",
//   "Boldore",
//   "Brionne",
//   "Carkol",
//   "Charjabug",
//   "Charmeleon",
//   "Cherubi",
//   "Clefairy",
//   "Combusken",
//   "Corsola-Galar",
//   "Corvisquire",
//   "Cosmoem",
//   "Cutiefly",
//   "Dartrix",
//   "Dottler",
//   "Dragonair",
//   "Drakloak",
//   "Drifloon",
//   "Drizzile",
//   "Duosion",
//   "Dusclops",
//   "Electabuzz",
//   "Fletchinder",
//   "Fraxure",
//   "Gabite",
//   "Gastly",
//   "Gloom",
//   "Golbat",
//   "Gothita",
//   "Gothorita",
//   "Grovyle",
//   "Gurdurr",
//   "Hakamo-o",
//   "Hattrem",
//   "Haunter",
//   "Herdier",
//   "Ivysaur",
//   "Jigglypuff",
//   "Kadabra",
//   "Kirlia",
//   "Klang",
//   "Krokorok",
//   "Kubfu",
//   "Lairon",
//   "Lampent",
//   "Linoone-Galar",
//   "Lombre",
//   "Loudred",
//   "Luxio",
//   "Machoke",
//   "Magmar",
//   "Magneton",
//   "Marill",
//   "Marshtomp",
//   "Metang",
//   "Metapod",
//   "Morgrem",
//   "Mr. Mime-Galar",
//   "Nidorina",
//   "Nidorino",
//   "Nuzleaf",
//   "Palpitoad",
//   "Pikachu",
//   "Piloswine",
//   "Poipole",
//   "Poliwhirl",
//   "Pupitar",
//   "Raboot",
//   "Rhydon",
//   "Roselia",
//   "Rufflet",
//   "Scraggy",
//   "Seadra",
//   "Sealeo",
//   "Shelgon",
//   "Sliggoo",
//   "Sneasel",
//   "Steenee",
//   "Swirlix",
//   "Tangela",
//   "Thwackey",
//   "Togetic",
//   "Torracat",
//   "Tranquill",
//   "Type: Null",
//   "Vanillish",
//   "Vibrava",
//   "Vullaby",
//   "Vulpix-Alola",
//   "Wartortle",
//   "Whirlipede",
//   "Woobat",
//   "Zweilous",
//   "Abra",
//   "Amaura",
//   "Anorith",
//   "Applin",
//   "Archen",
//   "Aron",
//   "Arrokuda",
//   "Axew",
//   "Azurill",
//   "Bagon",
//   "Baltoy",
//   "Barboach",
//   "Beldum",
//   "Bergmite",
//   "Binacle",
//   "Blipbug",
//   "Bonsly",
//   "Bounsweet",
//   "Bronzor",
//   "Budew",
//   "Bulbasaur",
//   "Buneary",
//   "Bunnelby",
//   "Carvanha",
//   "Caterpie",
//   "Charmander",
//   "Chewtle",
//   "Chinchou",
//   "Clauncher",
//   "Cleffa",
//   "Clobbopus",
//   "Combee",
//   "Corphish",
//   "Cosmog",
//   "Cottonee",
//   "Croagunk",
//   "Cubchoo",
//   "Cubone",
//   "Cufant",
//   "Darumaka",
//   "Darumaka-Galar",
//   "Deino",
//   "Dewpider",
//   "Diglett",
//   "Diglett-Alola",
//   "Dratini",
//   "Dreepy",
//   "Drilbur",
//   "Duskull",
//   "Dwebble",
//   "Eevee",
// ];
const randomPokemon = [
  "Abomasnow",
  "Absol",
  "Accelgor",
  "Aegislash",
  "Aegislash-Blade",
  "Aerodactyl",
  "Aggron",
  "Alakazam",
  "Alcremie-Gmax",
  "Altaria",
  "Amoonguss",
  "Appletun",
  "Appletun-Gmax",
  "Araquanid",
  "Arcanine",
  "Archeops",
  "Arctovish",
  "Arctozolt",
  "Armaldo",
  "Aromatisse",
  "Articuno",
  "Articuno-Galar",
  "Audino",
  "Aurorus",
  "Avalugg",
  "Azelf",
  "Azumarill",
  "Barbaracle",
  "Barraskewda",
  "Basculin",
  "Basculin-Blue-Striped",
  "Beartic",
  "Beheeyem",
  "Bellossom",
  "Bewear",
  "Bisharp",
  "Blacephalon",
  "Blastoise",
  "Blastoise-Gmax",
  "Blaziken",
  "Blissey",
  "Boltund",
  "Bouffalant",
  "Braviary",
  "Bronzong",
  "Butterfree",
  "Butterfree-Gmax",
  "Buzzwole",
  "Calyrex",
  "Calyrex-Ice",
  "Calyrex-Shadow",
  "Carbink",
  "Carracosta",
  "Celebi",
  "Celesteela",
  "Centiskorch",
  "Chandelure",
  "Chansey",
  "Charizard",
  "Cherrim",
  "Cinccino",
  "Cinderace",
  "Cinderace-Gmax",
  "Clawitzer",
  "Claydol",
  "Clefable",
  "Cloyster",
  "Coalossal-Gmax",
  "Cobalion",
  "Cofagrigus",
  "Comfey",
  "Conkeldurr",
  "Copperajah",
  "Copperajah-Gmax",
  "Corsola",
  "Corsola-Galar",
  "Corviknight",
  "Cradily",
  "Cramorant",
  "Crawdaunt",
  "Cresselia",
  "Crobat",
  "Crustle",
  "Cryogonal",
  "Cursola",
  "Darmanitan",
  "Darmanitan-Galar",
  "Darmanitan-Galar-Zen",
  "Decidueye",
  "Dedenne",
  "Delibird",
  "Dhelmise",
  "Dialga",
  "Diancie",
  "Diggersby",
  "Ditto",
  "Doublade",
  "Dracovish",
  "Dracozolt",
  "Dragalge",
  "Dragapult",
  "Dragonite",
  "Drampa",
  "Drapion",
  "Drednaw",
  "Drifblim",
  "Druddigon",
  "Dubwool",
  "Dugtrio",
  "Dugtrio-Alola",
  "Dunsparce",
  "Duraludon",
  "Durant",
  "Dusknoir",
  "Eiscue",
  "Eldegoss",
  "Electivire",
  "Emolga",
  "Entei",
  "Escavalier",
  "Espeon",
  "Eternatus",
  "Excadrill",
  "Exeggutor",
  "Exeggutor-Alola",
  "Exploud",
  "Falinks",
  "Farfetch’d",
  "Ferrothorn",
  "Flapple",
  "Flareon",
  "Flygon",
  "Froslass",
  "Frosmoth",
  "Gallade",
  "Galvantula",
  "Garbodor-Gmax",
  "Garchomp",
  "Gardevoir",
  "Gastrodon",
  "Genesect",
  "Genesect-Douse",
  "Gengar-Gmax",
  "Gigalith",
  "Giratina",
  "Giratina-Origin",
  "Glaceon",
  "Glalie",
  "Glastrier",
  "Golduck",
  "Golisopod",
  "Golurk",
  "Goodra",
  "Gothitelle",
  "Gourgeist",
  "Gourgeist-Large",
  "Gourgeist-Small",
  "Gourgeist-Super",
  "Grapploct",
  "Greedent",
  "Grimmsnarl",
  "Grimmsnarl-Gmax",
  "Groudon",
  "Gurdurr",
  "Guzzlord",
  "Gyarados",
  "Hatterene-Gmax",
  "Hawlucha",
  "Haxorus",
  "Heatmor",
  "Heatran",
  "Heliolisk",
  "Heracross",
  "Hippowdon",
  "Hitmonchan",
  "Hitmonlee",
  "Hitmontop",
  "Ho-Oh",
  "Hydreigon",
  "Incineroar",
  "Indeedee",
  "Indeedee-F",
  "Inteleon",
  "Inteleon-Gmax",
  "Jellicent",
  "Jirachi",
  "Jolteon",
  "Jynx",
  "Kabutops",
  "Kangaskhan",
  "Kartana",
  "Keldeo-Resolute",
  "Kingdra",
  "Kingler",
  "Klefki",
  "Klinklang",
  "Kommo-o",
  "Krookodile",
  "Kyogre",
  "Kyurem",
  "Kyurem-Black",
  "Kyurem-White",
  "Landorus",
  "Landorus-Therian",
  "Lanturn",
  "Lapras-Gmax",
  "Latias",
  "Latios",
  "Leafeon",
  "Lickilicky",
  "Liepard",
  "Lilligant",
  "Linoone",
  "Lopunny",
  "Lucario",
  "Ludicolo",
  "Lugia",
  "Lunala",
  "Lunatone",
  "Lurantis",
  "Luxray",
  "Lycanroc",
  "Lycanroc-Dusk",
  "Lycanroc-Midnight",
  "Machamp",
  "Magearna",
  "Magearna-Original",
  "Magmortar",
  "Magnezone",
  "Malamar",
  "Mamoswine",
  "Mandibuzz",
  "Manectric",
  "Mantine",
  "Maractus",
  "Marowak",
  "Marowak-Alola",
  "Marshadow",
  "Mawile",
  "Melmetal",
  "Meowstic",
  "Meowstic-F",
  "Mesprit",
  "Metagross",
  "Mew",
  "Mewtwo",
  "Mienshao",
  "Milotic",
  "Miltank",
  "Mimikyu",
  "Moltres",
  "Moltres-Galar",
  "Morpeko",
  "Mr. Mime",
  "Mr. Mime-Galar",
  "Mr. Rime",
  "Mudsdale",
  "Musharna",
  "Naganadel",
  "Necrozma",
  "Necrozma-Dawn-Wings",
  "Necrozma-Dusk-Mane",
  "Nidoking",
  "Nidoqueen",
  "Nihilego",
  "Ninetales",
  "Ninetales-Alola",
  "Ninjask",
  "Noctowl",
  "Noivern",
  "Obstagoon",
  "Octillery",
  "Omastar",
  "Oranguru",
  "Orbeetle",
  "Palkia",
  "Palossand",
  "Pangoro",
  "Passimian",
  "Pelipper",
  "Perrserker",
  "Persian",
  "Persian-Alola",
  "Pheromosa",
  "Pikachu",
  "Pincurchin",
  "Pinsir",
  "Politoed",
  "Poliwrath",
  "Polteageist",
  "Porygon-Z",
  "Porygon2",
  "Primarina",
  "Pyukumuku",
  "Quagsire",
  "Qwilfish",
  "Raichu",
  "Raichu-Alola",
  "Raikou",
  "Rapidash",
  "Rapidash-Galar",
  "Rayquaza",
  "Regice",
  "Regidrago",
  "Regieleki",
  "Regigigas",
  "Regirock",
  "Registeel",
  "Relicanth",
  "Reshiram",
  "Reuniclus",
  "Rhydon",
  "Rhyperior",
  "Ribombee",
  "Rillaboom",
  "Rillaboom-Gmax",
  "Roserade",
  "Rotom",
  "Rotom-Fan",
  "Rotom-Frost",
  "Rotom-Heat",
  "Rotom-Mow",
  "Rotom-Wash",
  "Runerigus",
  "Sableye",
  "Salamence",
  "Salazzle",
  "Sandaconda",
  "Sandslash",
  "Sandslash-Alola",
  "Sawk",
  "Sceptile",
  "Scizor",
  "Scolipede",
  "Scrafty",
  "Scyther",
  "Seaking",
  "Seismitoad",
  "Sharpedo",
  "Shedinja",
  "Shiftry",
  "Shiinotic",
  "Shuckle",
  "Sigilyph",
  "Silvally",
  "Silvally-Bug",
  "Silvally-Dark",
  "Silvally-Dragon",
  "Silvally-Electric",
  "Silvally-Fairy",
  "Silvally-Fighting",
  "Silvally-Fire",
  "Silvally-Flying",
  "Silvally-Ghost",
  "Silvally-Grass",
  "Silvally-Ground",
  "Silvally-Ice",
  "Silvally-Poison",
  "Silvally-Psychic",
  "Silvally-Rock",
  "Silvally-Steel",
  "Silvally-Water",
  "Sirfetch’d",
  "Skarmory",
  "Skuntank",
  "Slowbro",
  "Slowbro-Galar",
  "Slowking",
  "Slowking-Galar",
  "Slurpuff",
  "Snorlax",
  "Snorlax-Gmax",
  "Solgaleo",
  "Solrock",
  "Spectrier",
  "Spiritomb",
  "Stakataka",
  "Starmie",
  "Steelix",
  "Stonjourner",
  "Stoutland",
  "Stunfisk",
  "Stunfisk-Galar",
  "Sudowoodo",
  "Suicune",
  "Swampert",
  "Swoobat",
  "Sylveon",
  "Talonflame",
  "Tangrowth",
  "Tapu Bulu",
  "Tapu Fini",
  "Tapu Koko",
  "Tapu Lele",
  "Tauros",
  "Tentacruel",
  "Terrakion",
  "Thievul",
  "Throh",
  "Thundurus",
  "Thundurus-Therian",
  "Togedemaru",
  "Togekiss",
  "Torkoal",
  "Tornadus",
  "Tornadus-Therian",
  "Toxapex",
  "Toxicroak",
  "Toxtricity",
  "Toxtricity-Low-Key",
  "Trevenant",
  "Tsareena",
  "Turtonator",
  "Type: Null",
  "Tyranitar",
  "Tyrantrum",
  "Umbreon",
  "Unfezant",
  "Urshifu",
  "Urshifu-Gmax",
  "Urshifu-Rapid-Strike",
  "Urshifu-Rapid-Strike-Gmax",
  "Uxie",
  "Vanilluxe",
  "Vaporeon",
  "Venusaur",
  "Vespiquen",
  "Victini",
  "Vikavolt",
  "Vileplume",
  "Virizion",
  "Volcanion",
  "Volcarona",
  "Wailord",
  "Walrein",
  "Weavile",
  "Weezing",
  "Weezing-Galar",
  "Whimsicott",
  "Whiscash",
  "Wigglytuff",
  "Wishiwashi-School",
  "Wobbuffet",
  "Xatu",
  "Xerneas",
  "Xurkitree",
  "Yveltal",
  "Zacian",
  "Zacian-Crowned",
  "Zamazenta",
  "Zamazenta-Crowned",
  "Zapdos",
  "Zapdos-Galar",
  "Zarude",
  "Zarude-Dada",
  "Zekrom",
  "Zeraora",
  "Zoroark",
  "Zygarde",
  "Zygarde-10%",
];
export const makeRandomTeam = () => {
  const team = [];
  for (let i = 0; i <= 2; i++) {
    const pkmfloor =
      randomPokemon[Math.floor(Math.random() * randomPokemon.length)];
    const pkmceil =
      randomPokemon[Math.ceil(Math.random() * randomPokemon.length)];
    team.push(pkmfloor, pkmceil);
  }
  team[0] = team[0] + " (active)";
  return team;
};
