type Type = {
  normal: number;
  ground: number;
  rock: number;
  bug: number;
  ghost: number;
  steel: number;
  fighting: number;
  fire: number;
  flying: number;
  water: number;
  poison: number;
  grass: number;
  electric: number;
  psychic: number;
  ice: number;
  dragon: number;
  dark: number;
  fairy: number;
};
type SortedObject = {
  [key: number]: any[];
};
type ReadOnlyType = Readonly<{
  normal: number;
  ground: number;
  rock: number;
  bug: number;
  ghost: number;
  steel: number;
  fighting: number;
  fire: number;
  flying: number;
  water: number;
  poison: number;
  grass: number;
  electric: number;
  psychic: number;
  ice: number;
  dragon: number;
  dark: number;
  fairy: number;
}>;
const damageObj = {
  normal: {
    normal: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 0,
    steel: 1,
    fighting: 2,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  ground: {
    normal: 1,
    ground: 1,
    rock: 0.5,
    bug: 1,
    ghost: 1,
    steel: 1,
    fighting: 1,
    fire: 1,
    flying: 1,
    water: 2,
    poison: 0.5,
    grass: 2,
    electric: 0,
    psychic: 1,
    ice: 2,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  rock: {
    normal: 0.5,
    ground: 2,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 2,
    fighting: 2,
    fire: 0.5,
    flying: 0.5,
    water: 2,
    poison: 0.5,
    grass: 2,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  bug: {
    normal: 1,
    ground: 0.5,
    rock: 2,
    bug: 1,
    ghost: 1,
    steel: 1,
    fighting: 0.5,
    fire: 2,
    flying: 2,
    water: 1,
    poison: 1,
    grass: 0.5,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  ghost: {
    normal: 0,
    ground: 1,
    rock: 1,
    bug: 0.5,
    ghost: 2,
    steel: 1,
    fighting: 0,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 0.5,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 2,
    fairy: 1,
  },
  steel: {
    normal: 0.5,
    ground: 2,
    rock: 0.5,
    bug: 0.5,
    ghost: 1,
    steel: 0.5,
    fighting: 2,
    fire: 2,
    flying: 0.5,
    water: 1,
    poison: 0,
    grass: 0.5,
    electric: 1,
    psychic: 0.5,
    ice: 0.5,
    dragon: 0.5,
    dark: 1,
    fairy: 0.5,
  },
  fighting: {
    normal: 1,
    ground: 1,
    rock: 0.5,
    bug: 0.5,
    ghost: 1,
    steel: 1,
    fighting: 1,
    fire: 1,
    flying: 2,
    water: 1,
    poison: 1,
    grass: 1,
    electric: 1,
    psychic: 2,
    ice: 1,
    dragon: 1,
    dark: 0.5,
    fairy: 2,
  },
  fire: {
    normal: 1,
    ground: 2,
    rock: 2,
    bug: 0.5,
    ghost: 1,
    steel: 0.5,
    fighting: 1,
    fire: 0.5,
    flying: 1,
    water: 2,
    poison: 1,
    grass: 0.5,
    electric: 1,
    psychic: 1,
    ice: 0.5,
    dragon: 1,
    dark: 1,
    fairy: 0.5,
  },
  flying: {
    normal: 1,
    ground: 0,
    rock: 2,
    bug: 0.5,
    ghost: 1,
    steel: 1,
    fighting: 0.5,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 1,
    grass: 0.5,
    electric: 2,
    psychic: 1,
    ice: 2,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  water: {
    normal: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fighting: 1,
    fire: 0.5,
    flying: 1,
    water: 0.5,
    poison: 1,
    grass: 2,
    electric: 2,
    psychic: 1,
    ice: 0.5,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  poison: {
    normal: 1,
    ground: 2,
    rock: 1,
    bug: 0.5,
    ghost: 1,
    steel: 1,
    fighting: 0.5,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 0.5,
    grass: 0.5,
    electric: 1,
    psychic: 2,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 0.5,
  },
  grass: {
    normal: 1,
    ground: 0.5,
    rock: 1,
    bug: 2,
    ghost: 1,
    steel: 1,
    fighting: 1,
    fire: 2,
    flying: 2,
    water: 0.5,
    poison: 2,
    grass: 0.5,
    electric: 0.5,
    psychic: 1,
    ice: 2,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  electric: {
    normal: 1,
    ground: 2,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 0.5,
    fighting: 1,
    fire: 1,
    flying: 0.5,
    water: 1,
    poison: 1,
    grass: 1,
    electric: 0.5,
    psychic: 1,
    ice: 1,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  psychic: {
    normal: 1,
    ground: 1,
    rock: 1,
    bug: 2,
    ghost: 2,
    steel: 1,
    fighting: 0.5,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 1,
    grass: 1,
    electric: 1,
    psychic: 0.5,
    ice: 1,
    dragon: 1,
    dark: 2,
    fairy: 1,
  },
  ice: {
    normal: 1,
    ground: 1,
    rock: 2,
    bug: 1,
    ghost: 1,
    steel: 2,
    fighting: 2,
    fire: 2,
    flying: 1,
    water: 1,
    poison: 1,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 0.5,
    dragon: 1,
    dark: 1,
    fairy: 1,
  },
  dragon: {
    normal: 1,
    ground: 1,
    rock: 1,
    bug: 1,
    ghost: 1,
    steel: 1,
    fighting: 1,
    fire: 0.5,
    flying: 1,
    water: 0.5,
    poison: 1,
    grass: 0.5,
    electric: 0.5,
    psychic: 1,
    ice: 2,
    dragon: 2,
    dark: 1,
    fairy: 2,
  },
  dark: {
    normal: 1,
    ground: 1,
    rock: 1,
    bug: 2,
    ghost: 0.5,
    steel: 1,
    fighting: 2,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 1,
    grass: 1,
    electric: 1,
    psychic: 0,
    ice: 1,
    dragon: 1,
    dark: 0.5,
    fairy: 2,
  },
  fairy: {
    normal: 1,
    ground: 1,
    rock: 1,
    bug: 0.5,
    ghost: 1,
    steel: 2,
    fighting: 0.5,
    fire: 1,
    flying: 1,
    water: 1,
    poison: 2,
    grass: 1,
    electric: 1,
    psychic: 1,
    ice: 1,
    dragon: 0,
    dark: 0.5,
    fairy: 1,
  },
};
type KeyOfTypes = keyof Type;
const types: Array<KeyOfTypes> = [
  "normal",
  "ground",
  "rock",
  "bug",
  "ghost",
  "steel",
  "fighting",
  "fire",
  "flying",
  "water",
  "poison",
  "grass",
  "electric",
  "psychic",
  "ice",
  "dragon",
  "dark",
  "fairy",
];

const damageObjCreator = (pokemonTypes: Array<KeyOfTypes>): Type => {
  if (pokemonTypes.length === 1) {
    return damageObj[pokemonTypes[0]];
  }
  const combinedObj: Type = {
    normal: 0,
    ground: 0,
    rock: 0,
    bug: 0,
    ghost: 0,
    steel: 0,
    fighting: 0,
    fire: 0,
    flying: 0,
    water: 0,
    poison: 0,
    grass: 0,
    electric: 0,
    psychic: 0,
    ice: 0,
    dragon: 0,
    dark: 0,
    fairy: 0,
  };
  const type1: ReadOnlyType = damageObj[pokemonTypes[0]];
  const type2: ReadOnlyType = damageObj[pokemonTypes[1]];

  types.map((x) => (combinedObj[x] = type1[x] * type2[x]));
  return combinedObj;
};
export const displayDamageRelationsObj = (pokemonType: Array<KeyOfTypes>) => {
  let sortedObj: SortedObject = {
    0: [],
    0.25: [],
    0.5: [],
    1: [],
    2: [],
    4: [],
  };
  const typeObj = damageObjCreator(pokemonType);
  types.map((type) => sortedObj[typeObj[type]].push(type));
  return sortedObj;
};
